echo Executing NeXTTool to upload /usr/local/mindstorms/nxtOSEK/ecrobot/bios/nxt_bios_rom.rfw...
wineconsole /usr/local/mindstorms/bricxcc/nexttool/NeXTTool.exe /COM=usb -firmware=/usr/local/mindstorms/nxtOSEK/ecrobot/bios/nxt_bios_rom.rfw
