# Target specific macros
nxtOSEK = /usr/local/mindstorms/nxtOSEK
TARGET = main_OSEK
TARGET_SOURCES = \
	main.c algs.c
TOPPERS_OSEK_OIL_SOURCE = ./main.oil
ROOT=$(nxtOSEK)

# Don't modify below part
O_PATH ?= build
include $(nxtOSEK)/ecrobot/ecrobot.mak
